sudo: required

language: bash
services: docker

env:
  - DOCKER_IMAGE=murmur

script:
  - docker build -t ${DOCKER_IMAGE} .

after_script:
  - docker images
  - docker run -d -t ${DOCKER_IMAGE}
  - docker ps -a